#!/bin/bash

echo "enter the string"
read string1

echo "enter another string"
read string2

if [ "$string1" == "$string2" ]
then 
	echo " two strings are equal "
else 
	echo "two strings are not equal"
fi
